# Generated by Django 5.0.6 on 2024-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('name', models.TextField()),
                ('site', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
